version: "3"

networks:
  main:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - ./volumes/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - ./conf/hadoop.env
    ports:
      - 9870:9870
    networks:
      - main

  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-1
    depends_on: 
      - namenode
    volumes:
      - ./volumes/data/node-1:/hadoop/dfs/data
    env_file:
      - ./conf/hadoop.env
    ports:
      - 9864:9864
    networks:
      - main  

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2
    depends_on: 
      - namenode
    volumes:
      - ./volumes/data/node-2:/hadoop/dfs/data
    env_file:
      - ./conf/hadoop.env
    ports:
      - 9865:9864
    networks:
      - main  

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    ports:
      - 8088:8088
    depends_on: 
      - namenode
    env_file:
      - ./conf/hadoop.env
    volumes:
      - ./conf/core-site.xml:/etc/hadoop/core-site.xml
      - ./conf/yarn-site.xml:/etc/hadoop/yarn-site.xml
      - ./conf/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./conf/mapred-site.xml:/etc/hadoop/mapred-site.xml
    networks:
      - main

  nodemanager-1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager-1
    depends_on: 
      - resourcemanager
    env_file:
      - ./conf/hadoop.env
    deploy:
      mode: global
    labels:
       traefik.docker.network: hbase
       traefik.port: 8042
    ports:
      - 8042:8042
    networks:
      - main

  nodemanager-2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager-2
    depends_on: 
      - resourcemanager
    env_file:
      - ./conf/hadoop.env
    deploy:
      mode: global
    labels:
       traefik.docker.network: hbase
       traefik.port: 8042
    ports:
      - 8043:8042
    networks:
      - main

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    depends_on: 
      - resourcemanager
    env_file:
      - ./conf/hadoop.env
    volumes:
      - ./conf/core-site.xml:/etc/hadoop/core-site.xml
      - ./conf/yarn-site.xml:/etc/hadoop/yarn-site.xml
      - ./conf/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./conf/mapred-site.xml:/etc/hadoop/mapred-site.xml
    ports:
      - 8188:8188
    networks:
      - main

  spark-client:
    build:
      context: ./spark-client
      dockerfile: Dockerfile
    image: lordbagheera/spark-client:3.3.0-hadoop3.2.1-java8
    container_name: edge-1
    depends_on: 
      - historyserver
    volumes:
      - ./volumes/edge-1:/mnt/edge-1
    ports:
      - 2222:2222
      - 4040-4100:4040-4100
    environment:
      - TZ=America/Santiago
      - ROOT_PASSWORD=defaults
    env_file:
      - ./conf/hadoop.env
    networks:
      - main
  
  nifi:
    build:
      context: ./nifi
      dockerfile: Dockerfile
    image: lordbagheera/alpine-nifi:1.17.0
    container_name: nifi
    depends_on: 
      - hive-server   
    #volumes:
    #  - ./nificonf:/includes
    ports:
      - 8443:8443
    networks:
      - main
  ## PASSWORD ThisIsAnUnS3cur3P4ssw0rd

  jupyspark:
    image: jupyter/all-spark-notebook:spark-3.3.0
    container_name: jupyspark
    depends_on: 
      - hive-server    
    volumes:
      - ./volumes/jovian:/home/jovian
      - ./conf:/usr/local/cluster_conf
    env_file:
      - ./conf/jupyspark.env
    ports:
      - 8888:8888
    networks:
      - main

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on: 
      - namenode
      - hive-metastore
    env_file:
      - ./conf/hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - main

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    depends_on: 
      - namenode
      - hive-metastore-postgresql
    env_file:
      - ./conf/hadoop.env
    command: /opt/hive/bin/hive --service metastore
    #environment:
      #SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
      #hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - main

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    depends_on: 
      - historyserver
    networks:
      - main