version: "3"

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi-bigdata
    volumes:
      - ./shared:/mnt/shared
    ports:
      - "8443:8443"
      - "8000:8080"
    environment:
      - "SINGLE_USER_CREDENTIALS_USERNAME=root"
      - "SINGLE_USER_CREDENTIALS_PASSWORD=defaults"
      - "NIFI_WEB_PROXY_HOST=iroh, IROH, iroh:8443, IROH:8443"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    volumes:
      - ./shared:/mnt/shared
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    volumes:
      - ./shared:/mnt/shared
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    volumes:
      - ./shared:/mnt/shared
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  ftp-server:
    image: delfer/alpine-ftp-server
    container_name: bigdata-ftp
    volumes:
      - ./shared:/mnt/shared
      - ./shared/ftp:/ftp/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - "USERS=user|defaults"
    networks:
      - bigdata-net

  db:
    image: mysql
    container_name: mysql
    volumes:
      - ./shared:/mnt/shared
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=defaults
    networks:
      - bigdata-net

  shell:
    container_name: kurapika
    build:
      context: ./debian-spark-shell
      dockerfile: Dockerfile
    image: lordbagheera/debian-spark-shell:latest
    volumes:
      - ./shared:/mnt/shared
    ports:
      - "2222:2222"
    environment:
      - TZ=America/Santiago
      - ROOT_PASSWORD=defaults
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    volumes:
      - ./shared:/mnt/shared
    ports:
      - "8888:80"
    environment:
      - "PMA_ARBITRARY=1"
    networks:
      - bigdata-net

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - ./namenode:/hadoop/dfs/name
      - ./shared:/mnt/shared
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 8020:8020
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on: 
      - namenode
    volumes:
      - ./datanode:/hadoop/dfs/data
      - ./shared:/mnt/shared
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864
    networks:
      - bigdata-net  

networks:
  bigdata-net:
    driver: bridge